export const PROPOSAL_AUDIT_LOG = Symbol("PROPOSAL_AUDIT_LOG");
export const PROPOSAL_DRAFT_PROVIDER = Symbol("PROPOSAL_DRAFT_PROVIDER");
export const PROPOSAL_JOB_STORE = Symbol("PROPOSAL_JOB_STORE");
export const PROPOSAL_SERVICE = Symbol("PROPOSAL_SERVICE");
