export const CUSTOMER_ANALYSIS_AUDIT_LOG = Symbol("CUSTOMER_ANALYSIS_AUDIT_LOG");
export const CUSTOMER_ANALYSIS_CONFIG = Symbol("CUSTOMER_ANALYSIS_CONFIG");
export const CUSTOMER_ANALYSIS_SERVICE = Symbol("CUSTOMER_ANALYSIS_SERVICE");
